-- =========================================================
-- Chachees' Chai Cafe - Supabase PostgreSQL Schema & RLS
-- Run this script in the Supabase Dashboard -> SQL Editor
-- =========================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USERS PROFILE TABLE
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  uid text not null unique,
  email text not null,
  display_name text,
  photo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. MENU ITEMS TABLE
create table if not exists public.menu_items (
  id text primary key,
  name text not null,
  hindi_name text,
  category text not null,
  price integer not null,
  cad_price text,
  description text not null,
  tag text,
  is_veg boolean default true not null,
  spice_level text,
  serving_info text,
  customizable boolean default true,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ORDERS TABLE
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id text,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  delivery_address text,
  order_type text default 'takeaway' not null,
  items text not null, -- JSON string of items
  subtotal integer not null,
  tax integer not null,
  delivery_fee integer default 0 not null,
  total integer not null,
  status text default 'confirmed' not null,
  payment_method text default 'cash_on_delivery' not null,
  special_instructions text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABLE BOOKINGS / BAITHAK RESERVATIONS
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id text,
  full_name text not null,
  phone text not null,
  email text not null,
  location text not null,
  date text not null,
  session text not null,
  time_slot text not null,
  guests integer not null,
  zone text not null,
  occasion text,
  notes text,
  has_chai_flight boolean default false not null,
  status text default 'confirmed' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. REVIEWS TABLE
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id text,
  author text not null,
  initials text not null,
  role text default 'Chai Connoisseur',
  branch text not null,
  rating integer not null,
  text text not null,
  items_mentioned text,
  helpful_count integer default 0 not null,
  verified boolean default true not null,
  badge text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. CONTACT MESSAGES TABLE
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  topic text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.menu_items enable row level security;
alter table public.reviews enable row level security;
alter table public.orders enable row level security;
alter table public.bookings enable row level security;
alter table public.contact_messages enable row level security;

-- Public read policies
create policy "Allow public read access to menu items" on public.menu_items for select using (true);
create policy "Allow public read access to reviews" on public.reviews for select using (true);

-- Insert policies for orders, bookings, and contact messages
create policy "Allow insert access to orders" on public.orders for insert with check (true);
create policy "Allow select access to orders" on public.orders for select using (true);

create policy "Allow insert access to bookings" on public.bookings for insert with check (true);
create policy "Allow select access to bookings" on public.bookings for select using (true);
create policy "Allow update access to bookings" on public.bookings for update using (true);

create policy "Allow insert access to reviews" on public.reviews for insert with check (true);
create policy "Allow update helpful count on reviews" on public.reviews for update using (true);

create policy "Allow insert access to contact messages" on public.contact_messages for insert with check (true);
