import { db } from './index.ts';
import { menuItems, reviews } from './schema.ts';

export async function seedInitialDataIfNeeded() {
  try {
    const existingMenu = await db.select().from(menuItems).limit(1);
    if (existingMenu.length === 0) {
      console.log('Seeding initial menu items into Cloud SQL...');
      await db.insert(menuItems).values([
        {
          id: 'masala-chai',
          name: 'Masala Chai',
          hindiName: 'मसाला चाय',
          category: 'chai',
          price: 60,
          cadPrice: '4.50',
          description: 'Our signature secret spice blend: cinnamon, fragrant cardamom, dried cloves, and sharp crushed ginger simmered in fresh whole milk.',
          tag: 'Bestseller',
          isVeg: true,
          spiceLevel: 'Kadak',
          servingInfo: 'Served in Kulhad',
          customizable: true,
        },
        {
          id: 'cutting-chai',
          name: 'Cutting Chai',
          hindiName: 'कटिंग चाय',
          category: 'chai',
          price: 40,
          cadPrice: '3.25',
          description: 'Bold, aromatic, and deeply boiled strong half-cup cutting chai served piping hot in iconic ribbed Mumbai tapri glasses.',
          tag: 'Kadak Special',
          isVeg: true,
          spiceLevel: 'Kadak',
          servingInfo: 'Half Glass Kadak',
          customizable: true,
        },
        {
          id: 'adrak-chai',
          name: 'Adrak Chai',
          hindiName: 'अदरक चाय',
          category: 'chai',
          price: 55,
          cadPrice: '4.25',
          description: 'Soothing comfort brewed with copious amounts of fresh mortar-pestle pounded ginger root and creamy spiced Assam tea.',
          tag: 'Immunity',
          isVeg: true,
          spiceLevel: 'Medium',
          servingInfo: 'Crushed Fresh Ginger',
          customizable: true,
        },
        {
          id: 'elaichi-chai',
          name: 'Elaichi Chai',
          hindiName: 'इलायची चाय',
          category: 'chai',
          price: 60,
          cadPrice: '4.50',
          description: 'Fragrant green cardamoms sourced from Idukki hills, gently split and steeped for an intensely sweet floral infusion.',
          tag: 'Soothing Floral',
          isVeg: true,
          spiceLevel: 'Mild',
          servingInfo: 'Served in Clay Cup',
          customizable: true,
        },
        {
          id: 'kulhad-kesari-chai',
          name: 'Kulhad Kesari Chai',
          hindiName: 'कुल्हड़ केसरी चाय',
          category: 'chai',
          price: 85,
          cadPrice: '5.75',
          description: 'Royal, aromatic, and deeply boiled with Kashmiri saffron strands, slivered pistachios, and rich condensed milk.',
          tag: 'Chef Special',
          isVeg: true,
          spiceLevel: 'Mild',
          servingInfo: 'Earthen Clay Cup',
          customizable: true,
        },
        {
          id: 'sulaimani-chai',
          name: 'Sulaimani Chai',
          hindiName: 'सुलेमानी चाय',
          category: 'chai',
          price: 50,
          cadPrice: '3.75',
          description: 'Clear aromatic black tea infused with cracked black pepper, freshly squeezed lemon juice, mint, and pure wild honey.',
          tag: 'Digestive',
          isVeg: true,
          spiceLevel: 'Medium',
          servingInfo: 'Clear Glass Tumbler',
          customizable: true,
        },
        {
          id: 'bombay-grilled-cheese',
          name: 'Bombay Masala Grilled Cheese',
          hindiName: 'बॉम्बे ग्रिल्ड सैंडविच',
          category: 'snacks',
          price: 110,
          cadPrice: '7.50',
          description: 'Triple-decker sandwich loaded with sliced potatoes, cucumber, tomatoes, house mint chutney, and molten Amul cheese.',
          tag: 'Chef Pick',
          isVeg: true,
          spiceLevel: 'Feisty',
          servingInfo: 'Served Hot from Grill',
          customizable: true,
        },
        {
          id: 'punjabi-samosa',
          name: 'Crispy Punjabi Samosa (2 pcs)',
          hindiName: 'पंजाबी समोसा',
          category: 'snacks',
          price: 50,
          cadPrice: '4.95',
          description: 'Crispy carom-seed shortcrust pastry hand-stuffed with spiced potatoes, green peas, and whole coriander seeds. With saunth & mint dips.',
          tag: 'Popular',
          isVeg: true,
          spiceLevel: 'Medium',
          servingInfo: '2 Pieces + Dips',
          customizable: false,
        },
        {
          id: 'bun-maska-tutti-frutti',
          name: 'Warm Bun Maska Tutti Frutti',
          hindiName: 'बन मस्का टूटी-फ्रूटी',
          category: 'snacks',
          price: 70,
          cadPrice: '4.50',
          description: 'Pillowy soft baked sweet bun generously laden with salted butter, studded with sweet candied fruit, and warmed to golden perfection.',
          tag: 'Irani Classic',
          isVeg: true,
          spiceLevel: 'Mild',
          servingInfo: 'Chai dip essential',
          customizable: true,
        },
        {
          id: 'vada-pav',
          name: 'Mumbai Vada Pav',
          hindiName: 'मुंबई वड़ा पाव',
          category: 'snacks',
          price: 60,
          cadPrice: '4.25',
          description: 'Crisp spiced golden potato batata vada stuffed inside an airy pav, smothered with fiery red peanut-garlic thecha and fried green chilli.',
          tag: 'Mumbai Pride',
          isVeg: true,
          spiceLevel: 'Kadak',
          servingInfo: 'Includes fried chilli',
          customizable: false,
        },
        {
          id: 'classic-cold-coffee',
          name: 'Classic Cold Coffee Frappe',
          hindiName: 'कोल्ड कॉफी',
          category: 'cold',
          price: 120,
          cadPrice: '6.95',
          description: 'Thick, frothy, rich espresso blended with chilled whole milk, chicory essence, and dark Belgian cocoa drizzle.',
          tag: 'Chilled',
          isVeg: true,
          spiceLevel: 'Mild',
          servingInfo: '350ml Tall Jar',
          customizable: true,
        },
        {
          id: 'mango-lassi',
          name: 'Velvety Alphonso Mango Lassi',
          hindiName: 'आम की लस्सी',
          category: 'cold',
          price: 110,
          cadPrice: '6.25',
          description: 'Velvety hung curd blended with 100% natural Ratnagiri Alphonso mango pulp, crushed pistachios, and saffron infusion.',
          tag: 'Chilled Delight',
          isVeg: true,
          spiceLevel: 'Mild',
          servingInfo: 'Thick & Creamy 300ml',
          customizable: false,
        },
        {
          id: 'chai-combo-box',
          name: 'Chai Party Combo Box (For Two)',
          hindiName: 'चाय कॉम्बो बॉक्स',
          category: 'combos',
          price: 240,
          cadPrice: '12.95',
          description: '2 Hot Kulhad Masala Chais + 2 Crispy Punjabi Samosas with dips + 1 Warm Bun Maska Tutti Frutti. Perfect for sharing.',
          tag: 'Save 25%',
          isVeg: true,
          spiceLevel: 'Medium',
          servingInfo: 'Feeds 2 · All Bestsellers',
          customizable: true,
        },
      ]);
      console.log('Seeded initial menu items successfully.');
    }

    const existingReviews = await db.select().from(reviews).limit(1);
    if (existingReviews.length === 0) {
      console.log('Seeding initial community reviews into Cloud SQL...');
      await db.insert(reviews).values([
        {
          author: 'Ananya Mukherjee',
          initials: 'AM',
          role: 'Bandra Regular • 84 visits',
          branch: 'Bandra West, Mumbai',
          rating: 5,
          text: 'The Masala Chai in clay kulhad reminds me so vividly of morning chai in Lucknow. The balance of ginger and green cardamom is immaculate—not too sweet, perfectly spiced, and comforting beyond words. The Bun Maska is toasted to perfection.',
          itemsMentioned: 'Masala Kulhad Chai, Bun Maska, Kolkata Earthen Cup',
          helpfulCount: 42,
          verified: true,
          badge: 'Dine-in Regular',
        },
        {
          author: 'Rohan Sharma',
          initials: 'RS',
          role: 'Indiranagar Visitor',
          branch: 'Indiranagar, Bengaluru',
          rating: 5,
          text: 'Found my go-to work cafe! Super fast Wi-Fi, peaceful music, and the Sulaimani Chai with lemon and mint kept me energized through back-to-back meetings. The Chilli Cheese Toast has molten cheddar goodness that is dangerously addictive.',
          itemsMentioned: 'Sulaimani Mint Chai, Chilli Cheese Toast, Work Friendly',
          helpfulCount: 38,
          verified: true,
          badge: 'Digital Nomad',
        },
        {
          author: 'Pooja Verma',
          initials: 'PV',
          role: 'Delhi CP Regular',
          branch: 'Connaught Place, Delhi',
          rating: 5,
          text: 'Best Bun Maska in town! The bun is feather soft and they don’t skimp on real butter. Combined with the signature Adrak Chai, it’s instant rainy day happiness. Staff remembers your exact sweetness level!',
          itemsMentioned: 'Fresh Adrak Chai, Warm Bun Maska, Heritage Ambiance',
          helpfulCount: 56,
          verified: true,
          badge: 'Tea Connoisseur',
        },
      ]);
      console.log('Seeded initial reviews successfully.');
    }
  } catch (error) {
    console.error('Initial seeding notice (non-fatal):', error);
  }
}
